# Generated by Django 5.0.4 on 2024-07-28 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_bairro_remove_cliente_complemento_and_more'),
        ('produto', '0002_produto_estado_alter_produto_quantidade_and_more'),
        ('vendas', '0002_alter_venda_options_remove_venda_qtd_total_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itensvenda',
            options={},
        ),
        migrations.RemoveField(
            model_name='itensvenda',
            name='preco_total',
        ),
        migrations.RemoveField(
            model_name='itensvenda',
            name='preco_unitario',
        ),
        migrations.RemoveField(
            model_name='venda',
            name='estado',
        ),
        migrations.AddField(
            model_name='itensvenda',
            name='preco_venda',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='itensvenda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produto.produto'),
        ),
        migrations.AlterField(
            model_name='itensvenda',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='venda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='data_venda',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='venda',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
