# Generated by Django 5.0.4 on 2024-09-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0005_alter_itensvenda_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('paga', 'Paga')], default='paga', max_length=10),
        ),
    ]
