# Generated by Django 5.0.4 on 2024-05-21 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField(default=1)),
                ('preco_compra', models.FloatField(verbose_name='Preço Compra:')),
                ('preco_venda', models.FloatField(verbose_name='Preço Venda:')),
                ('preco_promocional', models.FloatField(blank=True, null=True, verbose_name='Preço Promoção:')),
                ('descricao', models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição:')),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
    ]
