# Generated by Django 5.0.4 on 2024-05-06 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('preco_compra', models.FloatField(verbose_name='Preço_compra')),
                ('preco_venda', models.FloatField(verbose_name='Preço_venda')),
                ('descricao_curta', models.TextField(blank=True, max_length=255, null=True)),
                ('preco_marketing_promocional', models.FloatField(default=0, verbose_name='Preço Promo.')),
            ],
        ),
    ]
