# Generated by Django 5.0.4 on 2024-05-15 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_alter_produto_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='descricao_curta',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='produto',
            old_name='preco_marketing_promocional',
            new_name='preco_promocional',
        ),
    ]
