# Generated by Django 5.0.4 on 2024-10-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0003_remove_produto_preco_promocional_remove_produto_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_promocional',
            field=models.FloatField(blank=True, null=True, verbose_name='Preço Promoção:'),
        ),
        migrations.AddField(
            model_name='produto',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug:'),
        ),
    ]
