# Generated by Django 5.0.4 on 2024-05-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0005_alter_produto_preco_promocional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Descrição:'),
        ),
    ]
