# Generated by Django 5.0.4 on 2024-07-27 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='divida',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default='teste@gmail.com', max_length=40, verbose_name='E-mail'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.CharField(max_length=30),
        ),
    ]
