# Generated by Django 5.0.4 on 2024-07-03 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_cpf_alter_cliente_endereco_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='divida',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='numero',
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(default=1, max_length=40, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.CharField(max_length=30),
        ),
    ]
