# Generated by Django 5.0.4 on 2024-10-19 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_cpf_alter_cliente_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='nome_cliente',
            field=models.CharField(max_length=30, verbose_name='Nome do Cliente'),
        ),
    ]
